"""Define the committed corpus file lists (DEV-200, HOLDOUT-100, PERF-10K).

    python -m verosim_harness.sample_corpora [--data-root DIR] [--out-dir corpora]

Deterministic: source basename lists are sorted, each corpus uses its own
string-seeded random.Random, so reruns over unchanged data reproduce the
committed lists byte-for-byte (modulo the dated header). Stdlib only.

Sampling rule: stages 0/1 only. Paths are emitted
relative to the data root. Pair lists are TSV `pred_xml<TAB>gt_krn` (pred=xml,
gt=krn, recorded in D14).
"""

from __future__ import annotations

import argparse
import datetime
import random
import sys
from pathlib import Path

from . import DEFAULT_DATA_ROOT

DEV_N = 200
HOLDOUT_LIEDER_N = 100
PERF_N = 10_000


def find_pairs(data_root: Path, dataset: str) -> list[tuple[str, str]]:
    """Sorted (xml_relpath, krn_relpath) pairs matched by basename."""
    xml_dir = data_root / "train" / dataset / "0_raw_xml"
    krn_dir = data_root / "train" / dataset / "1_kern_conversions"
    xml_bases = {p.stem for p in xml_dir.glob("*.xml")}
    krn_bases = {p.stem for p in krn_dir.glob("*.krn")}
    return [
        (
            f"train/{dataset}/0_raw_xml/{base}.xml",
            f"train/{dataset}/1_kern_conversions/{base}.krn",
        )
        for base in sorted(xml_bases & krn_bases)
    ]


def list_krn(data_root: Path, dataset: str) -> list[str]:
    krn_dir = data_root / "train" / dataset / "1_kern_conversions"
    return sorted(
        f"train/{dataset}/1_kern_conversions/{p.name}" for p in krn_dir.glob("*.krn")
    )


def write_list(path: Path, header_lines: list[str], rows: list[str]) -> None:
    date = datetime.date.today().isoformat()
    with open(path, "w", encoding="utf-8") as f:
        f.write("# generated by harness/verosim_harness/sample_corpora.py\n")
        f.write(f"# date: {date}\n")
        for line in header_lines:
            f.write(f"# {line}\n")
        for row in rows:
            f.write(row + "\n")
    print(f"wrote {path} ({len(rows)} rows)", file=sys.stderr)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data-root", default=DEFAULT_DATA_ROOT, required=not DEFAULT_DATA_ROOT, type=Path)
    ap.add_argument("--out-dir", default="corpora", type=Path)
    args = ap.parse_args(argv)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    # --- DEV-200 + HOLDOUT-100 from openscore-lieder (disjoint by construction) ---
    lieder = find_pairs(args.data_root, "openscore-lieder")
    dev = random.Random("verosim-dev200").sample(lieder, DEV_N)
    remainder = [p for p in lieder if p not in set(dev)]
    holdout_lieder = random.Random("verosim-holdout100").sample(remainder, HOLDOUT_LIEDER_N)
    assert not set(dev) & set(holdout_lieder), "DEV-200 and HOLDOUT-100 overlap"

    musetrainer = find_pairs(args.data_root, "musetrainer")

    write_list(
        args.out_dir / "dev200.tsv",
        [
            "seed: verosim-dev200",
            f"source: openscore-lieder 0_raw_xml <-> 1_kern_conversions ({len(lieder)} pairs)",
            "columns: pred_xml<TAB>gt_krn",
        ],
        ["\t".join(pair) for pair in dev],
    )
    write_list(
        args.out_dir / "holdout100.tsv",
        [
            "seed: verosim-holdout100 (sampled from the post-DEV-200 remainder; "
            "disjointness from dev200.tsv asserted at generation)",
            f"source: openscore-lieder remainder ({len(remainder)} pairs) "
            f"+ all {len(musetrainer)} musetrainer pairs",
            "columns: pred_xml<TAB>gt_krn",
            "FINAL ACCEPTANCE ONLY - never used during debugging",
        ],
        ["\t".join(pair) for pair in holdout_lieder + musetrainer],
    )

    # --- PERF-10K from pdmx + grandstaff kern conversions, proportional split ---
    pdmx = list_krn(args.data_root, "pdmx")
    grandstaff = list_krn(args.data_root, "grandstaff")
    pdmx_n = round(PERF_N * len(pdmx) / (len(pdmx) + len(grandstaff)))
    grandstaff_n = PERF_N - pdmx_n
    perf = random.Random("verosim-perf10k-pdmx").sample(pdmx, pdmx_n) + random.Random(
        "verosim-perf10k-grandstaff"
    ).sample(grandstaff, grandstaff_n)

    write_list(
        args.out_dir / "perf10k.txt",
        [
            "seeds: verosim-perf10k-pdmx, verosim-perf10k-grandstaff",
            f"source: pdmx 1_kern_conversions ({len(pdmx)} files, {pdmx_n} sampled) "
            f"+ grandstaff 1_kern_conversions ({len(grandstaff)} files, {grandstaff_n} sampled)",
            "proportional split; pre-cleaning stage, deliberately adversarial input",
        ],
        perf,
    )

    # --- all lieder kern, unsampled (R1 keys off lieder coverage) ---
    lieder_krn = list_krn(args.data_root, "openscore-lieder")
    write_list(
        args.out_dir / "lieder_all_krn.txt",
        [f"source: all openscore-lieder 1_kern_conversions ({len(lieder_krn)} files), unsampled"],
        lieder_krn,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
