#pragma once

// Keep the broad Verovio surface local to extraction internals. Public
// extraction headers forward-declare Verovio where they can.
#include "accid.h"
#include "artic.h"
#include "barline.h"
#include "beam.h"
#include "beamspan.h"
#include "chord.h"
#include "clef.h"
#include "doc.h"
#include "dynam.h"
#include "gracegrp.h"
#include "hairpin.h"
#include "keysig.h"
#include "layer.h"
#include "layerelement.h"
#include "measure.h"
#include "mensur.h"
#include "metersig.h"
#include "note.h"
#include "object.h"
#include "octave.h"
#include "rest.h"
#include "score.h"
#include "scoredef.h"
#include "sb.h"
#include "slur.h"
#include "staff.h"
#include "staffdef.h"
#include "timeinterface.h"
#include "tuplet.h"
#include "vrv.h"
